import type { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Chicken Curry Cut - Small Pieces',
    slug: 'chicken-curry-cut-small',
    category: 'Fresh Cuts',
    description: 'Tender, small pieces of chicken, perfect for quick curries and stir-fries. A fresh product, ideal for everyday cooking.',
    variants: [
      { name: '500g', price: 150, stock: 50 },
      { name: '1kg', price: 280, stock: 30 },
      { name: '1.5kg', price: 420, stock: 20 },
    ],
    images: ['https://picsum.photos/600/400?random=1'],
    reviews: [
      { id: 'r1', author: 'Suman', rating: 5, comment: 'Very fresh and tender!', date: '2023-10-10' },
    ],
  },
  {
    id: '2',
    name: 'Chicken Curry Cut - Large Pieces',
    slug: 'chicken-curry-cut-large',
    category: 'Fresh Cuts',
    description: 'Hearty, large chunks of chicken for rich, flavorful dishes like biryani or stews. A fresh product for special meals.',
    variants: [
      { name: '500g', price: 160, stock: 45 },
      { name: '1kg', price: 300, stock: 25 },
      { name: '1.5kg', price: 450, stock: 15 },
    ],
    images: ['https://picsum.photos/600/400?random=2'],
    reviews: [],
  },
  {
    id: '3',
    name: 'Chicken Keema (Mince)',
    slug: 'chicken-keema',
    category: 'Fresh Cuts',
    description: 'Finely minced chicken, versatile for patties, fillings, or keema curry. A fresh product that cooks quickly.',
    variants: [
      { name: '500g', price: 180, stock: 40 },
      { name: '1kg', price: 340, stock: 20 },
    ],
    images: ['https://picsum.photos/600/400?random=3'],
    reviews: [
      { id: 'r2', author: 'Amit', rating: 5, comment: 'Excellent quality keema.', date: '2023-10-11' },
    ],
  },
  {
    id: '4',
    name: 'Chicken Drumsticks',
    slug: 'chicken-drumsticks',
    category: 'Fresh Cuts',
    description: 'Juicy and flavorful chicken drumsticks, a favorite for grilling, frying, or baking. A fresh product for fun meals.',
    variants: [
      { name: '500g', price: 170, stock: 60 },
      { name: '1kg', price: 320, stock: 35 },
    ],
    images: ['https://picsum.photos/600/400?random=4'],
    reviews: [],
  },
  {
    id: '5',
    name: 'Chicken Breast - Boneless',
    slug: 'chicken-breast-boneless',
    category: 'Boneless',
    description: 'Lean and tender boneless chicken breast fillets. A fresh, healthy option perfect for grilling, salads, and sandwiches.',
    variants: [
      { name: '500g', price: 200, stock: 55 },
      { name: '1kg', price: 380, stock: 30 },
    ],
    images: ['https://picsum.photos/600/400?random=5'],
    reviews: [
      { id: 'r3', author: 'Rina', rating: 5, comment: 'Always fresh and perfectly trimmed.', date: '2023-10-12' },
    ],
  },
  {
    id: '6',
    name: 'Chicken Giblets (Liver, Stomach & Neck)',
    slug: 'chicken-giblets',
    category: 'Organ Meats',
    description: 'A combination of chicken liver, gizzard, and neck. A fresh product, rich in nutrients and ideal for traditional dishes.',
    variants: [
      { name: '500g', price: 120, stock: 30 },
    ],
    images: ['https://picsum.photos/600/400?random=6'],
    reviews: [],
  },
  {
    id: '7',
    name: 'Whole Chicken (700g - 900g)',
    slug: 'whole-chicken',
    category: 'Specialty',
    description: 'A fresh, whole chicken perfect for roasting or grilling. The centerpiece for any family feast or special occasion.',
    variants: [
      { name: '1 pc (700-900g)', price: 350, stock: 15 },
    ],
    images: ['https://picsum.photos/600/400?random=7'],
    reviews: [],
  },
  {
    id: '8',
    name: 'Chicken Leg - Boneless',
    slug: 'chicken-leg-boneless',
    category: 'Boneless',
    description: 'Succulent boneless chicken leg meat, known for its flavor and moisture. A fresh product, excellent for tikkas and curries.',
    variants: [
      { name: '500g', price: 210, stock: 40 },
      { name: '1kg', price: 400, stock: 20 },
    ],
    images: ['https://picsum.photos/600/400?random=8'],
    reviews: [],
  },
  {
    id: '9',
    name: 'Country Chicken (Desi)',
    slug: 'country-chicken',
    category: 'Specialty',
    description: 'Authentic Desi chicken with a uniquely rich flavor and firm texture. A fresh, premium product for traditional recipes.',
    variants: [
      { name: '1kg', price: 550, stock: 10 },
    ],
    images: ['https://picsum.photos/600/400?random=9'],
    reviews: [],
  },
  {
    id: '10',
    name: 'Dog Food (Chicken)',
    slug: 'dog-food-chicken',
    category: 'More',
    description: 'Freshly prepared chicken parts suitable for pets. A healthy and natural source of protein for your furry friend.',
    variants: [
      { name: '1kg', price: 150, stock: 50 },
    ],
    images: ['https://picsum.photos/600/400?random=10'],
    reviews: [],
  },
  {
    id: '11',
    name: 'Chicken Wings',
    slug: 'chicken-wings',
    category: 'Fresh Cuts',
    description: 'The perfect appetizer or party snack. Fresh chicken wings, ready for your favorite sauce or marinade.',
    variants: [
      { name: '500g (With Skin)', price: 160, stock: 30 },
      { name: '500g (Without Skin)', price: 170, stock: 30 },
    ],
    images: ['https://picsum.photos/600/400?random=11'],
    reviews: [],
  },
];
